### ISSUE TITLE
[Feature Request] Steam

### ISSUE THREAD

**Issue by Lionirdeadman** [orels1/ORELS-Cogs#5]
- Images could be displayed in the top right corner of the embed.

**Comment by orels1** [comment]
But I have those 🤔 
https://github.com/orels1/ORELS-Cogs/blob/master/steam/steam.py#L133

**Comment by Lionirdeadman** [comment]
![image](https://cloud.githubusercontent.com/assets/20693713/22397720/fc8f52f4-e545-11e6-9675-a454c3aaedcb.png)
Well, they don't show for me atleast.. That's weird.

**Comment by Lionirdeadman** [comment]
So, still no solution to this?

**Comment by orels1** [comment]
Yeah, sadly it seems like it's your local issue. It shows 100% correct for everyone using the cog (or at least I didn't have anyone complain), and I personally use this cog across 4 differrent bots and it works fine. Sadly it's hard for me to debug something I can't catch personally

**Comment by Lionirdeadman** [comment]
Since now you use links, this issue can be closed.
